[project]
name = "family-insurance-doc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.35.3",
    "pdfplumber>=0.11.7",
    "pydantic-ai>=1.0.15",
    "ripgrepy>=2.2.0",
]
